// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1991.SwerveDrive;

import org.usfirst.frc1991.SwerveDrive.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    public JoystickButton nextMode;
    public JoystickButton previousMode;
    public static Joystick logitechGamepad;

    public OI() {
        logitechGamepad = new Joystick(0);
        nextMode = new JoystickButton(logitechGamepad, 2);
        nextMode.whenPressed(new NextSwerveMode());
        previousMode = new JoystickButton(logitechGamepad, 3);
        previousMode.whenPressed(new PreviousSwerveMode());
        SmartDashboard.putData("nextSwerveMode", new NextSwerveMode());
        SmartDashboard.putData("DriveWithGamepad", new DriveWithGamepad());
    }

    public static Joystick getGamepad() {
    	return logitechGamepad;
    }
}
